In [ ]:
name = 'raza'
#12gender = 'M'
_fname = 'Umesh'
last_name = 'peter'
print(name, _fname, last_name)

raza Umesh peter

In [ ]:
DAY-2

#Integer : Any whole number(+ve or -ve) is called as integer

int1 = 1947
print(int1)
print(type(int1))

int2 = -1947
print(int2)
print(type(int2))

#Float : any combination of whole or fractional number

flt1 = 3.1415
print(flt1)
print(type(flt1))

flt2 = -3.1415
print(flt2)
print(type(flt2))

#complex : Combination of integer or float and imagenory number integer or float is called as complex

cmplx1 = 2 +3j
print(cmplx1)
print(type(cmplx1))

#Boolean : True or Flase

bool1 = True
print(bool1)
print(type(bool1))

bool2 = False
print(bool2)
print(type(bool2))

#string : any combination inside 'a' or "b"(single or double quotes)
#any combination inside triple single quotes
#any combination inside triple double quotes

str1 = 'python program'
print(str1)
print(type(str1))

str2 = "python program"
print(str2)
print(type(str2))

str3 = '''python program'''
print(str3)
print(type(str3))

str4 =  """python program"""
print(str4)
print(type(str4))

a = 2
b = 'raza'
c= "khan"
d = True
print(type(a))

str4 = 'Hows is your class going?', "did you understand", '''best of luck'''
print(type(str4))

#List
#1. List is mutable
#2.List is represented by square brackets[]

lst1 = [12,13,14,15,16,17,18,19,20]
print(lst1)
print(type(lst1))

#Tuple
#Tuple is inmutable
#is represented by circular bracket()

tup1 = (1,2,3,4,5,6,7)
print(tup1)
print(type(tup1))

#set
#is combintion of unique values
#collection of unordered element
#is represented by curly bracket{}
#set is mutable

set1 = {'a','b','c,','d','e','f',1,2,3,'!','@','#',}
print(set1)
print(type(set1))

set2 = {'hi', 'my', 'name', 'is', 'raza', 'taking', 'bootcamp',0,1,8,9,2023, True, False}
print(set2)
print(type(set2))

dict1 = {'a':'apple',
         'b': 'banana',
         'c': 'cherries'}

print(dict1)
print(type(dict1))

#dict2 = [lst1{'fruits', 'nuts',}]
#dict3 = (set1{'egg', 'cheese', 1,2,3})
#dict4 = (tup1{1,2,3,'b'})
#print(dict2, dict3, dict4)
#print(type(dict2, dict3, dict4))


#to find individual index
str1 = 'DataScienceBootcamp'
print(str1)
print(type(str1))
print(len(str1))

print(str1[0])
print(str1[1])
print(str1[2])
print(str1[3])
print(str1[4])
print(str1[4])
print(str1[5])
print(str1[6])
print(str1[7])
print(str1[8])
print(str1[9])
print(str1[10])
print(str1[11])

str1[0:7:1], str1[7:16:1]

str1 = 'srinivasaRamanujanAiyanagar'
print(str1[::])
print(str1[0::])
print(str1[:len(str1):])
print(str1[::1])

print(str1[:9:])

print(str1[9:18:])

print(str1[18::])

name_basket = 'Incomesavingexpenses'
print(name_basket[::])
print(name_basket[0::])
print(name_basket[:len(name_basket):])
print(name_basket[::1])
print(name_basket[:6:])
print(name_basket[6:12:])
print(name_basket[12::])




str1 = 'peppa prefer python programming'
print(str1)
print(type(str1))
print(len(str1))

print(str1[0])
print(str1[1])
print(str1[2])
print(str1[3])
print(str1[4])
print(str1[5])
print(str1[6])
print(str1[7])
print(str1[8])
print(str1[9])
print(str1[10])
print(str1[11])
print(str1[12])
print(str1[13])
print(str1[14])

print(str1[0:5][5:12][12:18][18:28])
print(str1[::-1])

#to pick only lasr three column from huge data
print(str1[-1:-12:-1][-13:-19:-1][-20:-26:-1][-27:-32:-1])